### ISSUE TITLE
Ruleset ignored due to bad selector

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/gochanges#4]
**Describe the bug**
After done `make up`, go to localhost:8080. The CSS is not loaded because (opening the console) `Ruleset ignored due to bad selector`.

**To Reproduce**
1. `make up`
2. Go to http://localhost:8080
3. Open the console

**Expected behavior**
CSS loaded and attached properly

**Desktop (please complete the following information):**
 - OS: Linux Lubuntu 20.04
 - Browser mozilla firefox
 - Version 76.01

**Comment by edoardottt** [comment]
Switching CSS from external to internal all works fine. But how I can do with images?... 

This would be the last solution. I don't like internal CSS.

**Comment by korableg** [comment]
@edoardottt hi, pull request: https://github.com/edoardottt/gochanges/pull/6

**Comment by edoardottt** [comment]
Thanks @korableg !! Now all works fine. :+1:

**Comment by korableg** [comment]
@edoardottt ☮ bro. If you have any more problems please contact me.
