### ISSUE TITLE
I know it is archived but I get "500 | Internal Server Error" whenever trying to add anything

### ISSUE THREAD

**Issue by certrik** [edoardottt/gochanges#7]
Ubuntu 20.04
`make up` works without errors.
Access to http://127.0.0.1:8080 works without errors.
Whenever I try to add an email-address or a website e.g. https://www.cnet.com/news/ I get "500 | Internal Server Error" .
In the terminal mongodb seems to get the input but wehn reloading main page nothing is shown.

I know the repo is archived but I really like to give it a try. Probably you can help me with the issue. I don't get it.

**Comment by edoardottt** [comment]
Hi! I confirm you that you're not doing something wrong.
I started coding this just for fun, but I didn't finish :/

Few things are missing, but they are crucial for the functionalities.. By the way there are a lot finished and well mantained identical projects. Try them, 
sorry for the inconvenient, I can't continue it now :/

- https://github.com/n1trux/awesome-sysadmin#monitoring
- https://github.com/statping/statping
- https://github.com/topics/website-monitor
- https://github.com/brotandgames/ciao
- https://github.com/710leo/urlooker
- https://github.com/ParryQiu/GuGuJianKong
- https://github.com/JuanmaMenendez/website-change-monitor

edoardottt
